name: Bug Report
description: File a bug report
      
      
        
#title: "Bug: "
      
      
        
labels: [type: bug]
      
      
        
body:
      
      
        
  - type: input
      
      
        
    id: version
      
      
        
    attributes:
      
      
        
      label: Version Information
      
      
        
      description: What version (commit hash and/or branch) of Galacticraft are you using?
      
      
        
      placeholder: 4cb9a5d
      
      
        
    validations:
      
      
        
      required: true
      
      
        
  - type: textarea
      
      
        
    id: what-happened
      
      
        
    attributes:
      
      
        
      label: What happened?
      
      
        
      description: Also tell us, what did you expect to happen?
      
      
        
      placeholder: Tell us what you see!
      
      
        
      value: "A bug happened!"
      
      
        
    validations:
      
      
        
      required: true
      
      
        
  - type: input
      
      
        
    id: logs
      
      
        
    attributes:
      
      
        
      label: Log or Crash Report
      
      
        
      description: Please upload your log (latest.log or crash report) to [Github Gist](https://gist.github.com/)
      
      
        
      placeholder: https://gist.github.com/ghost/1a79a4d60de6718e8e5b326e338ae533
      
      
        
    validations:
      
      
        
      required: true
      
      
        
  - type: textarea
      
      
        


      
      
        
    id: what-happened
      
      
        


      
      
        
    attributes:
      
      
        


      
      
        
      label: What happened?
      
      
        


      
      
        
      description: Also tell us, what did you expect to happen?
      
      
        


      
      
        
      placeholder: Tell us what you see!
      
      
        


      
      
        
      value: "A bug happened!"
      
      
        


      
      
        
    validations:
      
      
        


      
      
        
      required: true
      
      
        


      
      
        
  - type: textarea
      
      
        
    id: logs
      
      
        
    attributes:
      
      
        
      label: Relevant log output
      
      
        
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      
      
        
      render: shell
      
      
        
  - type: checkboxes
      
      
        
    id: terms
      
      
        
    attributes:
      
      
        
      label: Code of Conduct
      
      
        
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      
      
        
      options:
      
      
        
        - label: I agree to follow this project's Code of Conduct
      
      
        
          required: true
      
        
